services:
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
    environment:
      - AUDIT_ENABLED_SERVERS=${AUDIT_ENABLED_SERVERS}
      - COMMAND_PREFIX=${COMMAND_PREFIX}
      - CUSTOM_STATUS=${CUSTOM_STATUS}
      - DATABASE_URL=${DATABASE_URL}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - LOTTERY_ODDS=${LOTTERY_ODDS}
      - QUEUE_MAX_SOUNDS=${QUEUE_MAX_SOUNDS}
      - REACTION_TARGET_IDS=${REACTION_TARGET_IDS}
      - REACTION_TARGET_ODDS=${REACTION_TARGET_ODDS}
