services:
  discord_bot:
    build:
      context: .
      dockerfile: ./docker/discord_bot/Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
    environment:
      - AUDIT_ENABLED_SERVERS=${AUDIT_ENABLED_SERVERS}
      - CUSTOM_STATUS=${CUSTOM_STATUS}
      - DATABASE_URL=${DATABASE_URL}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - LOTTERY_ODDS=${LOTTERY_ODDS}
      - QUEUE_MAX_SOUNDS=${QUEUE_MAX_SOUNDS}
      - REACTION_TARGET_IDS=${REACTION_TARGET_IDS}
      - REACTION_TARGET_ODDS=${REACTION_TARGET_ODDS}
      - REDIS_URL=${REDIS_URL}
      - SOUNDCLOUD_CLIENT_ID=${SOUNDCLOUD_CLIENT_ID}
      - SOUNDCLOUD_CLIENT_SECRET=${SOUNDCLOUD_CLIENT_SECRET}
      - WEBDRIVER_PORT=${WEBDRIVER_PORT}
  worker:
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile
      args:
        - DATABASE_URL=${DATABASE_URL}
    environment:
      - AUDIT_ENABLED_SERVERS=${AUDIT_ENABLED_SERVERS}
      - CUSTOM_STATUS=${CUSTOM_STATUS}
      - DATABASE_URL=${DATABASE_URL}
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - LOTTERY_ODDS=${LOTTERY_ODDS}
      - QUEUE_MAX_SOUNDS=${QUEUE_MAX_SOUNDS}
      - REACTION_TARGET_IDS=${REACTION_TARGET_IDS}
      - REACTION_TARGET_ODDS=${REACTION_TARGET_ODDS}
      - REDIS_URL=${REDIS_URL}
      - SOUNDCLOUD_CLIENT_ID=${SOUNDCLOUD_CLIENT_ID}
      - SOUNDCLOUD_CLIENT_SECRET=${SOUNDCLOUD_CLIENT_SECRET}
      - WEBDRIVER_PORT=${WEBDRIVER_PORT}
  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4-alpine
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx4G # 4GB heap size
      - SERVER_PORT=${LAVALINK_PORT}
      - LAVALINK_SERVER_PASSWORD=${LAVALINK_PASSWORD}
    volumes:
      - ./lavalink/application.yml:/opt/Lavalink/application.yml
    expose:
      - ${LAVALINK_PORT}
    ports:
      - "${LAVALINK_PORT}:${LAVALINK_PORT}"
